# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Zadok the Priest
# Can be used to add a meta tag to the HTML header
site_author: "Nathan @nazzacode Sharp"

nav:
  - Home: index.md
  - About: about.md
  - Blog:
      "Blog": blog/blog_index.md
      "The Future of Work": blog/the_future_of_work.md

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/safety-goggles

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue grey
      accent: light blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: grey
      accent: grey

    # primary: indigo
    # accent: pink

  font: # set some nicer custom fonts! (latex/futuristic)
    text: Jura
    # text: Arvo
    # text: Ubuntu
    # text: Varela Round
    # text: Sen
    code: DM Mono
    # code: Roboto Mono
    # code: JetBrains Mono
    # code: Ubuntu Mono
    # code: Source Code Pro
    #

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.follow
    # - navigation.sections
    # - header.autohide

extra_css:
  # - css/mkdocs-material-themes/gruvbox_colors.css
  - stylesheets/extra.css
  - docs/css/mkdocs-material-themes/onedark_colors.css
  # - docs/css/mkdocs-material-themes/material_theme.css

extra_javascript:
  - javascript/extra.js
